// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IQiyiBidResponse.proto

package protocol.iqiyi;

public final class IQiyiBidResponse {
  private IQiyiBidResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SettlementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 version = 1;
    boolean hasVersion();
    int getVersion();
    
    // required bytes price = 2;
    boolean hasPrice();
    com.google.protobuf.ByteString getPrice();
    
    // optional bytes auth = 3;
    boolean hasAuth();
    com.google.protobuf.ByteString getAuth();
  }
  public static final class Settlement extends
      com.google.protobuf.GeneratedMessage
      implements SettlementOrBuilder {
    // Use Settlement.newBuilder() to construct.
    private Settlement(Builder builder) {
      super(builder);
    }
    private Settlement(boolean noInit) {}
    
    private static final Settlement defaultInstance;
    public static Settlement getDefaultInstance() {
      return defaultInstance;
    }
    
    public Settlement getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Settlement_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Settlement_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getVersion() {
      return version_;
    }
    
    // required bytes price = 2;
    public static final int PRICE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getPrice() {
      return price_;
    }
    
    // optional bytes auth = 3;
    public static final int AUTH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString auth_;
    public boolean hasAuth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getAuth() {
      return auth_;
    }
    
    private void initFields() {
      version_ = 0;
      price_ = com.google.protobuf.ByteString.EMPTY;
      auth_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, auth_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, auth_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Settlement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.iqiyi.IQiyiBidResponse.Settlement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.iqiyi.IQiyiBidResponse.SettlementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Settlement_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Settlement_fieldAccessorTable;
      }
      
      // Construct using protocol.iqiyi.IQiyiBidResponse.Settlement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        auth_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.iqiyi.IQiyiBidResponse.Settlement.getDescriptor();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Settlement getDefaultInstanceForType() {
        return protocol.iqiyi.IQiyiBidResponse.Settlement.getDefaultInstance();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Settlement build() {
        protocol.iqiyi.IQiyiBidResponse.Settlement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protocol.iqiyi.IQiyiBidResponse.Settlement buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protocol.iqiyi.IQiyiBidResponse.Settlement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Settlement buildPartial() {
        protocol.iqiyi.IQiyiBidResponse.Settlement result = new protocol.iqiyi.IQiyiBidResponse.Settlement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.auth_ = auth_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.iqiyi.IQiyiBidResponse.Settlement) {
          return mergeFrom((protocol.iqiyi.IQiyiBidResponse.Settlement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protocol.iqiyi.IQiyiBidResponse.Settlement other) {
        if (other == protocol.iqiyi.IQiyiBidResponse.Settlement.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasAuth()) {
          setAuth(other.getAuth());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPrice()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              price_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              auth_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 version = 1;
      private int version_ ;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes price = 2;
      private com.google.protobuf.ByteString price_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getPrice() {
        return price_;
      }
      public Builder setPrice(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = getDefaultInstance().getPrice();
        onChanged();
        return this;
      }
      
      // optional bytes auth = 3;
      private com.google.protobuf.ByteString auth_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasAuth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getAuth() {
        return auth_;
      }
      public Builder setAuth(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        auth_ = value;
        onChanged();
        return this;
      }
      public Builder clearAuth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        auth_ = getDefaultInstance().getAuth();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.iqiyi.Settlement)
    }
    
    static {
      defaultInstance = new Settlement(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.iqiyi.Settlement)
  }
  
  public interface BidOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Bid> {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string impid = 2;
    boolean hasImpid();
    String getImpid();
    
    // required int32 price = 3;
    boolean hasPrice();
    int getPrice();
    
    // required string adm = 6;
    boolean hasAdm();
    String getAdm();
    
    // required string crid = 10;
    boolean hasCrid();
    String getCrid();
    
    // optional int32 startdelay = 16;
    boolean hasStartdelay();
    int getStartdelay();
    
    // optional bool is_precision_advertising = 17 [default = false];
    boolean hasIsPrecisionAdvertising();
    boolean getIsPrecisionAdvertising();
  }
  public static final class Bid extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Bid> implements BidOrBuilder {
    // Use Bid.newBuilder() to construct.
    private Bid(Builder builder) {
      super(builder);
    }
    private Bid(boolean noInit) {}
    
    private static final Bid defaultInstance;
    public static Bid getDefaultInstance() {
      return defaultInstance;
    }
    
    public Bid getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Bid_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Bid_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string impid = 2;
    public static final int IMPID_FIELD_NUMBER = 2;
    private java.lang.Object impid_;
    public boolean hasImpid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getImpid() {
      java.lang.Object ref = impid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          impid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImpidBytes() {
      java.lang.Object ref = impid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        impid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int32 price = 3;
    public static final int PRICE_FIELD_NUMBER = 3;
    private int price_;
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPrice() {
      return price_;
    }
    
    // required string adm = 6;
    public static final int ADM_FIELD_NUMBER = 6;
    private java.lang.Object adm_;
    public boolean hasAdm() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getAdm() {
      java.lang.Object ref = adm_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          adm_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAdmBytes() {
      java.lang.Object ref = adm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        adm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string crid = 10;
    public static final int CRID_FIELD_NUMBER = 10;
    private java.lang.Object crid_;
    public boolean hasCrid() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getCrid() {
      java.lang.Object ref = crid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          crid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getCridBytes() {
      java.lang.Object ref = crid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        crid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 startdelay = 16;
    public static final int STARTDELAY_FIELD_NUMBER = 16;
    private int startdelay_;
    public boolean hasStartdelay() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getStartdelay() {
      return startdelay_;
    }
    
    // optional bool is_precision_advertising = 17 [default = false];
    public static final int IS_PRECISION_ADVERTISING_FIELD_NUMBER = 17;
    private boolean isPrecisionAdvertising_;
    public boolean hasIsPrecisionAdvertising() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public boolean getIsPrecisionAdvertising() {
      return isPrecisionAdvertising_;
    }
    
    private void initFields() {
      id_ = "";
      impid_ = "";
      price_ = 0;
      adm_ = "";
      crid_ = "";
      startdelay_ = 0;
      isPrecisionAdvertising_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImpid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAdm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCrid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<protocol.iqiyi.IQiyiBidResponse.Bid>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getImpidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(6, getAdmBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(10, getCridBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(16, startdelay_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(17, isPrecisionAdvertising_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getImpidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, price_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getAdmBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getCridBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, startdelay_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(17, isPrecisionAdvertising_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Bid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.iqiyi.IQiyiBidResponse.Bid prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          protocol.iqiyi.IQiyiBidResponse.Bid, Builder> implements protocol.iqiyi.IQiyiBidResponse.BidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Bid_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Bid_fieldAccessorTable;
      }
      
      // Construct using protocol.iqiyi.IQiyiBidResponse.Bid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        impid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        adm_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        crid_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        startdelay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        isPrecisionAdvertising_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.iqiyi.IQiyiBidResponse.Bid.getDescriptor();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Bid getDefaultInstanceForType() {
        return protocol.iqiyi.IQiyiBidResponse.Bid.getDefaultInstance();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Bid build() {
        protocol.iqiyi.IQiyiBidResponse.Bid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protocol.iqiyi.IQiyiBidResponse.Bid buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protocol.iqiyi.IQiyiBidResponse.Bid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Bid buildPartial() {
        protocol.iqiyi.IQiyiBidResponse.Bid result = new protocol.iqiyi.IQiyiBidResponse.Bid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.impid_ = impid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.adm_ = adm_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.crid_ = crid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.startdelay_ = startdelay_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.isPrecisionAdvertising_ = isPrecisionAdvertising_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.iqiyi.IQiyiBidResponse.Bid) {
          return mergeFrom((protocol.iqiyi.IQiyiBidResponse.Bid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protocol.iqiyi.IQiyiBidResponse.Bid other) {
        if (other == protocol.iqiyi.IQiyiBidResponse.Bid.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasImpid()) {
          setImpid(other.getImpid());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasAdm()) {
          setAdm(other.getAdm());
        }
        if (other.hasCrid()) {
          setCrid(other.getCrid());
        }
        if (other.hasStartdelay()) {
          setStartdelay(other.getStartdelay());
        }
        if (other.hasIsPrecisionAdvertising()) {
          setIsPrecisionAdvertising(other.getIsPrecisionAdvertising());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasImpid()) {
          
          return false;
        }
        if (!hasPrice()) {
          
          return false;
        }
        if (!hasAdm()) {
          
          return false;
        }
        if (!hasCrid()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              impid_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              price_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000008;
              adm_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000010;
              crid_ = input.readBytes();
              break;
            }
            case 128: {
              bitField0_ |= 0x00000020;
              startdelay_ = input.readInt32();
              break;
            }
            case 136: {
              bitField0_ |= 0x00000040;
              isPrecisionAdvertising_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string impid = 2;
      private java.lang.Object impid_ = "";
      public boolean hasImpid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getImpid() {
        java.lang.Object ref = impid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          impid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImpid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        impid_ = value;
        onChanged();
        return this;
      }
      public Builder clearImpid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        impid_ = getDefaultInstance().getImpid();
        onChanged();
        return this;
      }
      void setImpid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        impid_ = value;
        onChanged();
      }
      
      // required int32 price = 3;
      private int price_ ;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPrice() {
        return price_;
      }
      public Builder setPrice(int value) {
        bitField0_ |= 0x00000004;
        price_ = value;
        onChanged();
        return this;
      }
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        price_ = 0;
        onChanged();
        return this;
      }
      
      // required string adm = 6;
      private java.lang.Object adm_ = "";
      public boolean hasAdm() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getAdm() {
        java.lang.Object ref = adm_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          adm_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAdm(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        adm_ = value;
        onChanged();
        return this;
      }
      public Builder clearAdm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        adm_ = getDefaultInstance().getAdm();
        onChanged();
        return this;
      }
      void setAdm(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        adm_ = value;
        onChanged();
      }
      
      // required string crid = 10;
      private java.lang.Object crid_ = "";
      public boolean hasCrid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getCrid() {
        java.lang.Object ref = crid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          crid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setCrid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        crid_ = value;
        onChanged();
        return this;
      }
      public Builder clearCrid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        crid_ = getDefaultInstance().getCrid();
        onChanged();
        return this;
      }
      void setCrid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        crid_ = value;
        onChanged();
      }
      
      // optional int32 startdelay = 16;
      private int startdelay_ ;
      public boolean hasStartdelay() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getStartdelay() {
        return startdelay_;
      }
      public Builder setStartdelay(int value) {
        bitField0_ |= 0x00000020;
        startdelay_ = value;
        onChanged();
        return this;
      }
      public Builder clearStartdelay() {
        bitField0_ = (bitField0_ & ~0x00000020);
        startdelay_ = 0;
        onChanged();
        return this;
      }
      
      // optional bool is_precision_advertising = 17 [default = false];
      private boolean isPrecisionAdvertising_ ;
      public boolean hasIsPrecisionAdvertising() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getIsPrecisionAdvertising() {
        return isPrecisionAdvertising_;
      }
      public Builder setIsPrecisionAdvertising(boolean value) {
        bitField0_ |= 0x00000040;
        isPrecisionAdvertising_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsPrecisionAdvertising() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isPrecisionAdvertising_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.iqiyi.Bid)
    }
    
    static {
      defaultInstance = new Bid(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.iqiyi.Bid)
  }
  
  public interface SeatbidOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .protocol.iqiyi.Bid bid = 1;
    java.util.List<protocol.iqiyi.IQiyiBidResponse.Bid> 
        getBidList();
    protocol.iqiyi.IQiyiBidResponse.Bid getBid(int index);
    int getBidCount();
    java.util.List<? extends protocol.iqiyi.IQiyiBidResponse.BidOrBuilder> 
        getBidOrBuilderList();
    protocol.iqiyi.IQiyiBidResponse.BidOrBuilder getBidOrBuilder(
        int index);
  }
  public static final class Seatbid extends
      com.google.protobuf.GeneratedMessage
      implements SeatbidOrBuilder {
    // Use Seatbid.newBuilder() to construct.
    private Seatbid(Builder builder) {
      super(builder);
    }
    private Seatbid(boolean noInit) {}
    
    private static final Seatbid defaultInstance;
    public static Seatbid getDefaultInstance() {
      return defaultInstance;
    }
    
    public Seatbid getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Seatbid_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Seatbid_fieldAccessorTable;
    }
    
    // repeated .protocol.iqiyi.Bid bid = 1;
    public static final int BID_FIELD_NUMBER = 1;
    private java.util.List<protocol.iqiyi.IQiyiBidResponse.Bid> bid_;
    public java.util.List<protocol.iqiyi.IQiyiBidResponse.Bid> getBidList() {
      return bid_;
    }
    public java.util.List<? extends protocol.iqiyi.IQiyiBidResponse.BidOrBuilder> 
        getBidOrBuilderList() {
      return bid_;
    }
    public int getBidCount() {
      return bid_.size();
    }
    public protocol.iqiyi.IQiyiBidResponse.Bid getBid(int index) {
      return bid_.get(index);
    }
    public protocol.iqiyi.IQiyiBidResponse.BidOrBuilder getBidOrBuilder(
        int index) {
      return bid_.get(index);
    }
    
    private void initFields() {
      bid_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getBidCount(); i++) {
        if (!getBid(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < bid_.size(); i++) {
        output.writeMessage(1, bid_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < bid_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bid_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.Seatbid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.iqiyi.IQiyiBidResponse.Seatbid prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Seatbid_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_Seatbid_fieldAccessorTable;
      }
      
      // Construct using protocol.iqiyi.IQiyiBidResponse.Seatbid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBidFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (bidBuilder_ == null) {
          bid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          bidBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.iqiyi.IQiyiBidResponse.Seatbid.getDescriptor();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Seatbid getDefaultInstanceForType() {
        return protocol.iqiyi.IQiyiBidResponse.Seatbid.getDefaultInstance();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Seatbid build() {
        protocol.iqiyi.IQiyiBidResponse.Seatbid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protocol.iqiyi.IQiyiBidResponse.Seatbid buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protocol.iqiyi.IQiyiBidResponse.Seatbid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protocol.iqiyi.IQiyiBidResponse.Seatbid buildPartial() {
        protocol.iqiyi.IQiyiBidResponse.Seatbid result = new protocol.iqiyi.IQiyiBidResponse.Seatbid(this);
        int from_bitField0_ = bitField0_;
        if (bidBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            bid_ = java.util.Collections.unmodifiableList(bid_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.bid_ = bid_;
        } else {
          result.bid_ = bidBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.iqiyi.IQiyiBidResponse.Seatbid) {
          return mergeFrom((protocol.iqiyi.IQiyiBidResponse.Seatbid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protocol.iqiyi.IQiyiBidResponse.Seatbid other) {
        if (other == protocol.iqiyi.IQiyiBidResponse.Seatbid.getDefaultInstance()) return this;
        if (bidBuilder_ == null) {
          if (!other.bid_.isEmpty()) {
            if (bid_.isEmpty()) {
              bid_ = other.bid_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBidIsMutable();
              bid_.addAll(other.bid_);
            }
            onChanged();
          }
        } else {
          if (!other.bid_.isEmpty()) {
            if (bidBuilder_.isEmpty()) {
              bidBuilder_.dispose();
              bidBuilder_ = null;
              bid_ = other.bid_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bidBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBidFieldBuilder() : null;
            } else {
              bidBuilder_.addAllMessages(other.bid_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getBidCount(); i++) {
          if (!getBid(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              protocol.iqiyi.IQiyiBidResponse.Bid.Builder subBuilder = protocol.iqiyi.IQiyiBidResponse.Bid.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addBid(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protocol.iqiyi.Bid bid = 1;
      private java.util.List<protocol.iqiyi.IQiyiBidResponse.Bid> bid_ =
        java.util.Collections.emptyList();
      private void ensureBidIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          bid_ = new java.util.ArrayList<protocol.iqiyi.IQiyiBidResponse.Bid>(bid_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.iqiyi.IQiyiBidResponse.Bid, protocol.iqiyi.IQiyiBidResponse.Bid.Builder, protocol.iqiyi.IQiyiBidResponse.BidOrBuilder> bidBuilder_;
      
      public java.util.List<protocol.iqiyi.IQiyiBidResponse.Bid> getBidList() {
        if (bidBuilder_ == null) {
          return java.util.Collections.unmodifiableList(bid_);
        } else {
          return bidBuilder_.getMessageList();
        }
      }
      public int getBidCount() {
        if (bidBuilder_ == null) {
          return bid_.size();
        } else {
          return bidBuilder_.getCount();
        }
      }
      public protocol.iqiyi.IQiyiBidResponse.Bid getBid(int index) {
        if (bidBuilder_ == null) {
          return bid_.get(index);
        } else {
          return bidBuilder_.getMessage(index);
        }
      }
      public Builder setBid(
          int index, protocol.iqiyi.IQiyiBidResponse.Bid value) {
        if (bidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidIsMutable();
          bid_.set(index, value);
          onChanged();
        } else {
          bidBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setBid(
          int index, protocol.iqiyi.IQiyiBidResponse.Bid.Builder builderForValue) {
        if (bidBuilder_ == null) {
          ensureBidIsMutable();
          bid_.set(index, builderForValue.build());
          onChanged();
        } else {
          bidBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addBid(protocol.iqiyi.IQiyiBidResponse.Bid value) {
        if (bidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidIsMutable();
          bid_.add(value);
          onChanged();
        } else {
          bidBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addBid(
          int index, protocol.iqiyi.IQiyiBidResponse.Bid value) {
        if (bidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBidIsMutable();
          bid_.add(index, value);
          onChanged();
        } else {
          bidBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addBid(
          protocol.iqiyi.IQiyiBidResponse.Bid.Builder builderForValue) {
        if (bidBuilder_ == null) {
          ensureBidIsMutable();
          bid_.add(builderForValue.build());
          onChanged();
        } else {
          bidBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addBid(
          int index, protocol.iqiyi.IQiyiBidResponse.Bid.Builder builderForValue) {
        if (bidBuilder_ == null) {
          ensureBidIsMutable();
          bid_.add(index, builderForValue.build());
          onChanged();
        } else {
          bidBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllBid(
          java.lang.Iterable<? extends protocol.iqiyi.IQiyiBidResponse.Bid> values) {
        if (bidBuilder_ == null) {
          ensureBidIsMutable();
          super.addAll(values, bid_);
          onChanged();
        } else {
          bidBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearBid() {
        if (bidBuilder_ == null) {
          bid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bidBuilder_.clear();
        }
        return this;
      }
      public Builder removeBid(int index) {
        if (bidBuilder_ == null) {
          ensureBidIsMutable();
          bid_.remove(index);
          onChanged();
        } else {
          bidBuilder_.remove(index);
        }
        return this;
      }
      public protocol.iqiyi.IQiyiBidResponse.Bid.Builder getBidBuilder(
          int index) {
        return getBidFieldBuilder().getBuilder(index);
      }
      public protocol.iqiyi.IQiyiBidResponse.BidOrBuilder getBidOrBuilder(
          int index) {
        if (bidBuilder_ == null) {
          return bid_.get(index);  } else {
          return bidBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protocol.iqiyi.IQiyiBidResponse.BidOrBuilder> 
           getBidOrBuilderList() {
        if (bidBuilder_ != null) {
          return bidBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(bid_);
        }
      }
      public protocol.iqiyi.IQiyiBidResponse.Bid.Builder addBidBuilder() {
        return getBidFieldBuilder().addBuilder(
            protocol.iqiyi.IQiyiBidResponse.Bid.getDefaultInstance());
      }
      public protocol.iqiyi.IQiyiBidResponse.Bid.Builder addBidBuilder(
          int index) {
        return getBidFieldBuilder().addBuilder(
            index, protocol.iqiyi.IQiyiBidResponse.Bid.getDefaultInstance());
      }
      public java.util.List<protocol.iqiyi.IQiyiBidResponse.Bid.Builder> 
           getBidBuilderList() {
        return getBidFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.iqiyi.IQiyiBidResponse.Bid, protocol.iqiyi.IQiyiBidResponse.Bid.Builder, protocol.iqiyi.IQiyiBidResponse.BidOrBuilder> 
          getBidFieldBuilder() {
        if (bidBuilder_ == null) {
          bidBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol.iqiyi.IQiyiBidResponse.Bid, protocol.iqiyi.IQiyiBidResponse.Bid.Builder, protocol.iqiyi.IQiyiBidResponse.BidOrBuilder>(
                  bid_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          bid_ = null;
        }
        return bidBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.iqiyi.Seatbid)
    }
    
    static {
      defaultInstance = new Seatbid(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.iqiyi.Seatbid)
  }
  
  public interface BidResponseOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<BidResponse> {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // repeated .protocol.iqiyi.Seatbid seatbid = 2;
    java.util.List<protocol.iqiyi.IQiyiBidResponse.Seatbid> 
        getSeatbidList();
    protocol.iqiyi.IQiyiBidResponse.Seatbid getSeatbid(int index);
    int getSeatbidCount();
    java.util.List<? extends protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder> 
        getSeatbidOrBuilderList();
    protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder getSeatbidOrBuilder(
        int index);
    
    // optional int32 processing_time_ms = 4;
    boolean hasProcessingTimeMs();
    int getProcessingTimeMs();
  }
  public static final class BidResponse extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        BidResponse> implements BidResponseOrBuilder {
    // Use BidResponse.newBuilder() to construct.
    private BidResponse(Builder builder) {
      super(builder);
    }
    private BidResponse(boolean noInit) {}
    
    private static final BidResponse defaultInstance;
    public static BidResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BidResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_BidResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_BidResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .protocol.iqiyi.Seatbid seatbid = 2;
    public static final int SEATBID_FIELD_NUMBER = 2;
    private java.util.List<protocol.iqiyi.IQiyiBidResponse.Seatbid> seatbid_;
    public java.util.List<protocol.iqiyi.IQiyiBidResponse.Seatbid> getSeatbidList() {
      return seatbid_;
    }
    public java.util.List<? extends protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder> 
        getSeatbidOrBuilderList() {
      return seatbid_;
    }
    public int getSeatbidCount() {
      return seatbid_.size();
    }
    public protocol.iqiyi.IQiyiBidResponse.Seatbid getSeatbid(int index) {
      return seatbid_.get(index);
    }
    public protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder getSeatbidOrBuilder(
        int index) {
      return seatbid_.get(index);
    }
    
    // optional int32 processing_time_ms = 4;
    public static final int PROCESSING_TIME_MS_FIELD_NUMBER = 4;
    private int processingTimeMs_;
    public boolean hasProcessingTimeMs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getProcessingTimeMs() {
      return processingTimeMs_;
    }
    
    private void initFields() {
      id_ = "";
      seatbid_ = java.util.Collections.emptyList();
      processingTimeMs_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getSeatbidCount(); i++) {
        if (!getSeatbid(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<protocol.iqiyi.IQiyiBidResponse.BidResponse>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      for (int i = 0; i < seatbid_.size(); i++) {
        output.writeMessage(2, seatbid_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, processingTimeMs_);
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      for (int i = 0; i < seatbid_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, seatbid_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, processingTimeMs_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocol.iqiyi.IQiyiBidResponse.BidResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.iqiyi.IQiyiBidResponse.BidResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          protocol.iqiyi.IQiyiBidResponse.BidResponse, Builder> implements protocol.iqiyi.IQiyiBidResponse.BidResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_BidResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.iqiyi.IQiyiBidResponse.internal_static_protocol_iqiyi_BidResponse_fieldAccessorTable;
      }
      
      // Construct using protocol.iqiyi.IQiyiBidResponse.BidResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSeatbidFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (seatbidBuilder_ == null) {
          seatbid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          seatbidBuilder_.clear();
        }
        processingTimeMs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.iqiyi.IQiyiBidResponse.BidResponse.getDescriptor();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.BidResponse getDefaultInstanceForType() {
        return protocol.iqiyi.IQiyiBidResponse.BidResponse.getDefaultInstance();
      }
      
      public protocol.iqiyi.IQiyiBidResponse.BidResponse build() {
        protocol.iqiyi.IQiyiBidResponse.BidResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protocol.iqiyi.IQiyiBidResponse.BidResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protocol.iqiyi.IQiyiBidResponse.BidResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protocol.iqiyi.IQiyiBidResponse.BidResponse buildPartial() {
        protocol.iqiyi.IQiyiBidResponse.BidResponse result = new protocol.iqiyi.IQiyiBidResponse.BidResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (seatbidBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            seatbid_ = java.util.Collections.unmodifiableList(seatbid_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.seatbid_ = seatbid_;
        } else {
          result.seatbid_ = seatbidBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.processingTimeMs_ = processingTimeMs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.iqiyi.IQiyiBidResponse.BidResponse) {
          return mergeFrom((protocol.iqiyi.IQiyiBidResponse.BidResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protocol.iqiyi.IQiyiBidResponse.BidResponse other) {
        if (other == protocol.iqiyi.IQiyiBidResponse.BidResponse.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (seatbidBuilder_ == null) {
          if (!other.seatbid_.isEmpty()) {
            if (seatbid_.isEmpty()) {
              seatbid_ = other.seatbid_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureSeatbidIsMutable();
              seatbid_.addAll(other.seatbid_);
            }
            onChanged();
          }
        } else {
          if (!other.seatbid_.isEmpty()) {
            if (seatbidBuilder_.isEmpty()) {
              seatbidBuilder_.dispose();
              seatbidBuilder_ = null;
              seatbid_ = other.seatbid_;
              bitField0_ = (bitField0_ & ~0x00000002);
              seatbidBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSeatbidFieldBuilder() : null;
            } else {
              seatbidBuilder_.addAllMessages(other.seatbid_);
            }
          }
        }
        if (other.hasProcessingTimeMs()) {
          setProcessingTimeMs(other.getProcessingTimeMs());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getSeatbidCount(); i++) {
          if (!getSeatbid(i).isInitialized()) {
            
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder subBuilder = protocol.iqiyi.IQiyiBidResponse.Seatbid.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addSeatbid(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              processingTimeMs_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // repeated .protocol.iqiyi.Seatbid seatbid = 2;
      private java.util.List<protocol.iqiyi.IQiyiBidResponse.Seatbid> seatbid_ =
        java.util.Collections.emptyList();
      private void ensureSeatbidIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          seatbid_ = new java.util.ArrayList<protocol.iqiyi.IQiyiBidResponse.Seatbid>(seatbid_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.iqiyi.IQiyiBidResponse.Seatbid, protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder, protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder> seatbidBuilder_;
      
      public java.util.List<protocol.iqiyi.IQiyiBidResponse.Seatbid> getSeatbidList() {
        if (seatbidBuilder_ == null) {
          return java.util.Collections.unmodifiableList(seatbid_);
        } else {
          return seatbidBuilder_.getMessageList();
        }
      }
      public int getSeatbidCount() {
        if (seatbidBuilder_ == null) {
          return seatbid_.size();
        } else {
          return seatbidBuilder_.getCount();
        }
      }
      public protocol.iqiyi.IQiyiBidResponse.Seatbid getSeatbid(int index) {
        if (seatbidBuilder_ == null) {
          return seatbid_.get(index);
        } else {
          return seatbidBuilder_.getMessage(index);
        }
      }
      public Builder setSeatbid(
          int index, protocol.iqiyi.IQiyiBidResponse.Seatbid value) {
        if (seatbidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeatbidIsMutable();
          seatbid_.set(index, value);
          onChanged();
        } else {
          seatbidBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setSeatbid(
          int index, protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder builderForValue) {
        if (seatbidBuilder_ == null) {
          ensureSeatbidIsMutable();
          seatbid_.set(index, builderForValue.build());
          onChanged();
        } else {
          seatbidBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addSeatbid(protocol.iqiyi.IQiyiBidResponse.Seatbid value) {
        if (seatbidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeatbidIsMutable();
          seatbid_.add(value);
          onChanged();
        } else {
          seatbidBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addSeatbid(
          int index, protocol.iqiyi.IQiyiBidResponse.Seatbid value) {
        if (seatbidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSeatbidIsMutable();
          seatbid_.add(index, value);
          onChanged();
        } else {
          seatbidBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addSeatbid(
          protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder builderForValue) {
        if (seatbidBuilder_ == null) {
          ensureSeatbidIsMutable();
          seatbid_.add(builderForValue.build());
          onChanged();
        } else {
          seatbidBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addSeatbid(
          int index, protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder builderForValue) {
        if (seatbidBuilder_ == null) {
          ensureSeatbidIsMutable();
          seatbid_.add(index, builderForValue.build());
          onChanged();
        } else {
          seatbidBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllSeatbid(
          java.lang.Iterable<? extends protocol.iqiyi.IQiyiBidResponse.Seatbid> values) {
        if (seatbidBuilder_ == null) {
          ensureSeatbidIsMutable();
          super.addAll(values, seatbid_);
          onChanged();
        } else {
          seatbidBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearSeatbid() {
        if (seatbidBuilder_ == null) {
          seatbid_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          seatbidBuilder_.clear();
        }
        return this;
      }
      public Builder removeSeatbid(int index) {
        if (seatbidBuilder_ == null) {
          ensureSeatbidIsMutable();
          seatbid_.remove(index);
          onChanged();
        } else {
          seatbidBuilder_.remove(index);
        }
        return this;
      }
      public protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder getSeatbidBuilder(
          int index) {
        return getSeatbidFieldBuilder().getBuilder(index);
      }
      public protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder getSeatbidOrBuilder(
          int index) {
        if (seatbidBuilder_ == null) {
          return seatbid_.get(index);  } else {
          return seatbidBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder> 
           getSeatbidOrBuilderList() {
        if (seatbidBuilder_ != null) {
          return seatbidBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(seatbid_);
        }
      }
      public protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder addSeatbidBuilder() {
        return getSeatbidFieldBuilder().addBuilder(
            protocol.iqiyi.IQiyiBidResponse.Seatbid.getDefaultInstance());
      }
      public protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder addSeatbidBuilder(
          int index) {
        return getSeatbidFieldBuilder().addBuilder(
            index, protocol.iqiyi.IQiyiBidResponse.Seatbid.getDefaultInstance());
      }
      public java.util.List<protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder> 
           getSeatbidBuilderList() {
        return getSeatbidFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.iqiyi.IQiyiBidResponse.Seatbid, protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder, protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder> 
          getSeatbidFieldBuilder() {
        if (seatbidBuilder_ == null) {
          seatbidBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol.iqiyi.IQiyiBidResponse.Seatbid, protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder, protocol.iqiyi.IQiyiBidResponse.SeatbidOrBuilder>(
                  seatbid_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          seatbid_ = null;
        }
        return seatbidBuilder_;
      }
      
      // optional int32 processing_time_ms = 4;
      private int processingTimeMs_ ;
      public boolean hasProcessingTimeMs() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getProcessingTimeMs() {
        return processingTimeMs_;
      }
      public Builder setProcessingTimeMs(int value) {
        bitField0_ |= 0x00000004;
        processingTimeMs_ = value;
        onChanged();
        return this;
      }
      public Builder clearProcessingTimeMs() {
        bitField0_ = (bitField0_ & ~0x00000004);
        processingTimeMs_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protocol.iqiyi.BidResponse)
    }
    
    static {
      defaultInstance = new BidResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocol.iqiyi.BidResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_iqiyi_Settlement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_iqiyi_Settlement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_iqiyi_Bid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_iqiyi_Bid_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_iqiyi_Seatbid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_iqiyi_Seatbid_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_iqiyi_BidResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_iqiyi_BidResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026IQiyiBidResponse.proto\022\016protocol.iqiyi" +
      "\":\n\nSettlement\022\017\n\007version\030\001 \001(\r\022\r\n\005price" +
      "\030\002 \002(\014\022\014\n\004auth\030\003 \001(\014\"\221\001\n\003Bid\022\n\n\002id\030\001 \002(\t" +
      "\022\r\n\005impid\030\002 \002(\t\022\r\n\005price\030\003 \002(\005\022\013\n\003adm\030\006 " +
      "\002(\t\022\014\n\004crid\030\n \002(\t\022\022\n\nstartdelay\030\020 \001(\005\022\'\n" +
      "\030is_precision_advertising\030\021 \001(\010:\005false*\010" +
      "\010d\020\200\200\200\200\002\"+\n\007Seatbid\022 \n\003bid\030\001 \003(\0132\023.proto" +
      "col.iqiyi.Bid\"i\n\013BidResponse\022\n\n\002id\030\001 \002(\t" +
      "\022(\n\007seatbid\030\002 \003(\0132\027.protocol.iqiyi.Seatb" +
      "id\022\032\n\022processing_time_ms\030\004 \001(\005*\010\010d\020\200\200\200\200\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_iqiyi_Settlement_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_iqiyi_Settlement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_iqiyi_Settlement_descriptor,
              new java.lang.String[] { "Version", "Price", "Auth", },
              protocol.iqiyi.IQiyiBidResponse.Settlement.class,
              protocol.iqiyi.IQiyiBidResponse.Settlement.Builder.class);
          internal_static_protocol_iqiyi_Bid_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_iqiyi_Bid_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_iqiyi_Bid_descriptor,
              new java.lang.String[] { "Id", "Impid", "Price", "Adm", "Crid", "Startdelay", "IsPrecisionAdvertising", },
              protocol.iqiyi.IQiyiBidResponse.Bid.class,
              protocol.iqiyi.IQiyiBidResponse.Bid.Builder.class);
          internal_static_protocol_iqiyi_Seatbid_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protocol_iqiyi_Seatbid_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_iqiyi_Seatbid_descriptor,
              new java.lang.String[] { "Bid", },
              protocol.iqiyi.IQiyiBidResponse.Seatbid.class,
              protocol.iqiyi.IQiyiBidResponse.Seatbid.Builder.class);
          internal_static_protocol_iqiyi_BidResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_protocol_iqiyi_BidResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_iqiyi_BidResponse_descriptor,
              new java.lang.String[] { "Id", "Seatbid", "ProcessingTimeMs", },
              protocol.iqiyi.IQiyiBidResponse.BidResponse.class,
              protocol.iqiyi.IQiyiBidResponse.BidResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
